# Generated by Django 3.2 on 2021-04-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0003_device_macro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Macro',
        ),
        migrations.AddField(
            model_name='macro',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autonomica.device'),
        ),
    ]
