# Generated by Django 3.2 on 2021-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0005_alter_macro_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macro',
            name='user',
        ),
    ]
