# Generated by Django 3.2 on 2021-04-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0007_alter_device_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='screen',
        ),
    ]
