# Generated by Django 3.2 on 2021-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0008_rename_user_device_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
