# Generated by Django 3.2 on 2021-04-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0010_alter_macro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='category',
            field=models.CharField(choices=[('p', 'Projector'), ('s', 'Sound'), ('a', 'Audiotorium'), ('m', 'MediaBlock')], default='p', max_length=100),
        ),
    ]
