# Generated by Django 3.2 on 2021-04-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0011_alter_macro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
