# Generated by Django 3.2 on 2021-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0012_alter_todo_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
