# Generated by Django 3.2 on 2021-04-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0014_alter_macro_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macro',
            name='ip',
        ),
        migrations.AddField(
            model_name='macro',
            name='jnior',
            field=models.CharField(choices=[('n', 'None'), ('c', 'Cinema Application'), ('t', 'Tasker Application')], default='n', help_text='Use if macro is amed for Tasker or Cinema Application.', max_length=100),
        ),
        migrations.AlterField(
            model_name='macro',
            name='command',
            field=models.CharField(help_text='System command.', max_length=100),
        ),
        migrations.AlterField(
            model_name='macro',
            name='device',
            field=models.ForeignKey(help_text='Device category.', null=True, on_delete=django.db.models.deletion.CASCADE, to='autonomica.device'),
        ),
        migrations.AlterField(
            model_name='macro',
            name='name',
            field=models.CharField(help_text='Public name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='macro',
            name='screen',
            field=models.ForeignKey(help_text='Related to screen.', on_delete=django.db.models.deletion.CASCADE, to='autonomica.screen'),
        ),
        migrations.AlterField(
            model_name='macro',
            name='termination',
            field=models.CharField(blank=True, help_text='Termination String if any.', max_length=100),
        ),
    ]
