# Generated by Django 3.2 on 2021-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0015_auto_20210412_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cinema',
            field=models.BooleanField(blank=True, default=False, help_text='If Jnior is Cinema Application installed?'),
        ),
        migrations.AddField(
            model_name='device',
            name='tasker',
            field=models.BooleanField(blank=True, default=False, help_text='If Jnior is Tasker Application installed?'),
        ),
    ]
