# Generated by Django 3.2 on 2021-04-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0017_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='colors',
            field=models.CharField(choices=[('danger', 'Red'), ('success', 'Green'), ('info', 'Blue'), ('warning', 'Yellow')], default='danger', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autonomica.screen'),
        ),
    ]
