# Generated by Django 3.2 on 2021-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomica', '0019_auto_20210417_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='help',
            name='info',
            field=models.TextField(),
        ),
    ]
